### ISSUE TITLE
setWeights function error:index error

### ISSUE THREAD

**Issue by Mrliuzhengming** [shiruipan/TriDNR#3]
hi,i have a problem as follow: 
![1](https://cloud.githubusercontent.com/assets/24410626/26146127/a127944e-3b21-11e7-8bad-097762325c8f.png)
i print the index:
![2](https://cloud.githubusercontent.com/assets/24410626/26146338/662e5eda-3b22-11e7-9cd8-c00a6baaf1f8.png)
so ,i had this modify：
![3](https://cloud.githubusercontent.com/assets/24410626/26146159/bc12334a-3b21-11e7-8b3b-c56d99be1f7b.png)
it's work ,but i dont't know whether this is ok .i'm very appreciate if you can help.

**Comment by shiruipan** [comment]
Are you using the correct version of gensim? We use the gensim 0.12.0 for TriDNR.

**Comment by Mrliuzhengming** [comment]
hi,today i try to install in ubantu,use  pip install -r requirements.txt 
then when i run demo,have the follow problem:
///////////////////////////////////////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    import networkutils as net
  File "/home/TriDNR-master/networkutils.py", line 2, in <module>
    from gensim.models.doc2vec import Doc2Vec, Word2Vec
  File "/home/anaconda2/lib/python2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/home/anaconda2/lib/python2.7/site-packages/gensim/models/__init__.py", line 13, in <module>
    from .word2vec import Word2Vec
  File "/home/anaconda2/lib/python2.7/site-packages/gensim/models/word2vec.py", line 96, in <module>
    from gensim.models.word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION
  File "__init__.pxd", line 155, in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:9080)
ValueError: numpy.dtype has the wrong size, try recompiling
///////////////////////////////////////////////////////////////////////////////////////////////////
 what can i do for this?

**Comment by shiruipan** [comment]
I am not sure. May be you can try to remove your numpy and then install the
newest version of numpy.

2017-05-22 16:53 GMT+10:00 zhengming liu <notifications@github.com>:

**Comment by Mrliuzhengming** [comment]
@shiruipan ,thanks  a lot. it's work for me
